version: 1.0.0.{build}
image: Visual Studio 2019
configuration:
- Release
- Debug
platform: Any CPU
shallow_clone: true
install:
- ps: AppVeyor\install.ps1
before_build:
- cmd: nuget restore
build:
  project: MCPixelArtCrafter.sln
  verbosity: minimal
artifacts:
- path: MCPixelArtCrafterWPF\bin\Release
  name: MCPAC_WPF
- path: MCPixelArtCrafter\bin\Release
  name: MCPAC
deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: MCPAC $(AppVersion)
  description: "No changelog"
  auth_token:
    secure: VPJ8f2cGI95B4SnCa79ghR26EociVlfXmSzL/H8tnJoc1QugKl3mWGlEMf7lA6OO
  artifact: MCPAC_WPF,MCPAC
  draft: false
  prerelease: true
  on:
    configuration: Release
    appveyor_repo_tag: true